# Generated by Django 5.0.4 on 2024-04-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ctem_cafe', '0003_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
    ]
