# Generated by Django 5.0.4 on 2024-05-14 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ctem_cafe', '0004_remove_cliente_data_nascimento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='id',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Avaliacao3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.CharField(max_length=150)),
                ('avaliado', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
