# Generated by Django 5.0.4 on 2024-06-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ctem_cafe', '0011_tagusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro2',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=100)),
                ('nome_loja', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('arq', models.URLField()),
                ('concordo_termos', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
