Cypress.Commands.add('deleteAllUsers', () => {
    cy.exec('python delete.py', { failOnNonZeroExit: true })
});

describe('teste anunciarnovidades', () => {
    it('cenario1', () => {
        cy.visit('/');
        cy.exec('python manage.py migrate')
        cy.deleteAllUsers();

        cy.get(':nth-child(8)').click()
        cy.get('#inputFullName').type('Cafeteria do Zé')
        cy.get('#age4').type('25')
        cy.get('#inputgender4').select('Masculino')
        cy.get('.col-md-12 > .btn').click()
        cy.get('#inputEmail4').type('ze@gmail.com')
        cy.get('#inputPassword4').type('12345')
        cy.get(':nth-child(4) > #inputPassword4').type('12345')
        cy.get('#gridCheck').click()
        cy.get('[type="submit"]').click()
        cy.get('#inputEmail4').type('ze@gmail.com')
        cy.get('#inputPassword4').type('12345')
        cy.get('#inputStoreName').type('Cafeteria do Zé')
        cy.get('#inputAddress').type('Rua Conselheiro Theodoro')
        cy.get('#inputAddress2').type('105')
        cy.get('#inputNeighborhood').type('Zumbi')
        cy.get('#inputZip').type('50711030')
        cy.get('#gridCheck').click()
        cy.get('.btn').click()
        cy.get('#inputEmail4').type('Cafeteria do Zé')
        cy.get('#inputPassword4').type('12345')
        cy.get('[type="submit"]').click()
        cy.get('[href="/escrever_noticias/"] > .btn').click()
        cy.get('#titulo').type('Chá de Batata')
        cy.get('#description').type('Novo chá faz sucesso entre os internautas')
        cy.get('#foto').type('https://static.itdg.com.br/images/auto-auto/3e2c981f4413beee7bc0c7f0c74785d4/shutterstock-504515311-300x225.jpg')
        cy.get('.btn').click()
        cy.get('.m-2').click()
        cy.get('form > :nth-child(6)').click()
        cy.get('#inputFullName').type('Tonho')
        cy.get('#age4').type('28')
        cy.get('#inputgender4').select('Masculino')
        cy.get('.col-md-12 > .btn').click()
        cy.get('#inputEmail4').type('Tonho@gmail.com')
        cy.get('#inputPassword4').type('12345')
        cy.get(':nth-child(4) > #inputPassword4').type('12345')
        cy.get('#gridCheck').click()
        cy.get('[type="submit"]').click()
        cy.get('#inputEmail4').type('Tonho')
        cy.get('#inputPassword4').type('12345')
        cy.get('[type="submit"]').click()
    })
})